table Ingresos
	lineageTag: 7821cc01-ff4c-47c3-9e25-35618fa64c61

	column ID
		dataType: int64
		formatString: 0
		lineageTag: 1ec7b583-85c7-4b3f-ab5a-cf5d82986d57
		summarizeBy: count
		sourceColumn: ID

		annotation SummarizationSetBy = Automatic

	column 'Descripción proyectos'
		dataType: string
		lineageTag: 494def81-49bd-4aff-ba8a-04a6c673acee
		summarizeBy: none
		sourceColumn: Descripción proyectos

		annotation SummarizationSetBy = Automatic

	column Ingreso
		dataType: double
		lineageTag: 4d8d39d3-6ce3-479d-940e-cdc8ce1303d2
		summarizeBy: sum
		sourceColumn: Ingreso

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: c525e893-e09b-4d99-a64a-1ff3bb04f40b
		summarizeBy: none
		sourceColumn: Fecha

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Ingresos = m
		mode: import
		queryGroup: Modelo
		source =
				let
				    Origen = Excel.Workbook(File.Contents("C:\Users\maria\Downloads\Costo_Ingreso.xlsx"), null, true),
				    Ingresos_Sheet = Origen{[Item="Ingresos",Kind="Sheet"]}[Data],
				    #"Encabezados promovidos" = Table.PromoteHeaders(Ingresos_Sheet, [PromoteAllScalars=true]),
				    #"Tipo cambiado" = Table.TransformColumnTypes(#"Encabezados promovidos",{{"ID", Int64.Type}, {"Descripción proyectos", type text}, {"Ingreso", type number}, {"Fecha", type date}})
				in
				    #"Tipo cambiado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegación

